name: "Question"
description: "Ask a general question"
title: "[Question]: "
labels: ["question"]
assignees:
  - thepercentageguy
body:
  - type: textarea
    id: question
    attributes:
      label: Question
    validations:
      required: true
